"""Synthetic work-location data for demos when Microsoft Graph isn't available.

Returns the same response shape as `graph_calendar.work_location_by_day` so
callers can swap implementations transparently via the `USE_FAKE_CALENDAR=1`
env flag.

Data source: a JSON file at `api/data/fake_calendars.json` generated by the
seed script. Each user is keyed by both UPN and email and contains a list of
per-day verdicts derived from their `defaultWorkingPattern` (with light
variance to mimic real-world calendar drift).
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any

_DATA_PATH = Path(__file__).parent / "data" / "fake_calendars.json"

_cache: dict[str, list[dict[str, Any]]] | None = None


def _load() -> dict[str, list[dict[str, Any]]]:
    global _cache
    if _cache is not None:
        return _cache
    if not _DATA_PATH.exists():
        _cache = {}
        return _cache
    with _DATA_PATH.open() as f:
        payload = json.load(f)
    _cache = payload.get("users", {})
    return _cache


def mock_work_location_by_day(
    user_id: str, start_date: date, end_date: date
) -> list[dict[str, Any]]:
    """Drop-in replacement for graph_calendar.work_location_by_day."""
    users = _load()
    days_for_user = users.get(user_id) or users.get(user_id.lower()) or []
    by_date = {d["date"]: d for d in days_for_user}

    days: list[dict[str, Any]] = []
    current = start_date
    while current <= end_date:
        key = current.isoformat()
        entry = by_date.get(key)
        if entry is None:
            # No synthetic data for this user/date — return "unknown".
            days.append({"date": key, "location": "unknown", "source": None})
        else:
            days.append(entry)
        current = date.fromordinal(current.toordinal() + 1)
    return days
